#
# Makefile for plot widgets (Linux version)
#
CC=cc
AR=ar
# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
#CFLAGS = -g2 -DFUNCPROTO
CFLAGS=-O  -DUSE_DIRENT -DUSE_LPR_PRINT_CMD
LIBS=  -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11

include Makefile.common
