CC=cc
AR=ar

# For editres, add -DEDITRES to CFLAGS and -lXmu to LIBS
CFLAGS=-O  -DUSE_DIRENT -DUSE_LPR_PRINT_CMD
LIBS=  -lm -lXm -lXpm -lXext -lXt -lSM -lICE -lX11

NLIBDIR = ../linux_lib
NBINDIR = ../linux_bin

include Makefile.common
